ALTER TABLE person
ALTER COLUMN address
TYPE VARCHAR(200);

ALTER TABLE person
ALTER COLUMN phone_number
TYPE VARCHAR(20);

ALTER TABLE patient
ALTER COLUMN insurance
TYPE VARCHAR(50);

ALTER TABLE doctor
ALTER COLUMN hospital
TYPE VARCHAR(50);

ALTER TABLE drugs
ALTER COLUMN name
TYPE VARCHE(50);

ALTER TABLE drugs
ALTER COLUMN dosage
TYPE VARCHAR(20)

ALTER TABLE drugs
ALTER COLUMN type
TYPE VARCHAR(30);

ALTER TABLE appointment
ALTER COLUMN motive
TYPE VARCHAR(50);

